name: Build and Lint

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  build-lint:
    name: Build and Lint

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the source
        uses: actions/checkout@v4
        with:
          show-progress: false
          submodules: recursive

      - name: Audit Dependency
        run: yarn audit --audit-level moderate

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "21.7.1"
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile --prefer-offline

      - name: Next Build
        run: yarn run build

      - name: cloudflare Build
        run: npx @cloudflare/next-on-pages@1

      - name: Lint
        run: yarn run lint
