name: deploy on cloudflare pages
on:
  workflow_dispatch:
  schedule:
    - cron: "1,7,13 * * *"  #10時,16時,22時(JST=UTC+9)に実行
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: auth-gcal
    steps:
      - name: Checkout the source
        uses: actions/checkout@v4
        with:
          show-progress: false
          submodules: recursive

      - name: Audit Dependency
        run: yarn audit --audit-level moderate

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "21.7.1"
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile --prefer-offline

      - name: Build
        run: npx @cloudflare/next-on-pages@1
        env:
          CALENDAR_LESSON_ID: ${{ secrets.CALENDAR_LESSON_ID }}
          CALENDAR_SHINKAN_ID: ${{ secrets.CALENDAR_SHINKAN_ID }}
          GOOGLE_OAUTH_CLIENT_ID: ${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}
          GOOGLE_OAUTH_CLIENT_SECRET: ${{ secrets.GOOGLE_OAUTH_CLIENT_SECRET }}
          GOOGLE_OAUTH_REFRESH_TOKEN: ${{ secrets.GOOGLE_OAUTH_REFRESH_TOKEN }}
          TZ: ${{ secrets.TZ }}

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          projectName: ${{ secrets.CLOUDFLARE_PROJECT_NAME }}
          directory: .vercel/output/static
          gitHubToken: ${{ secrets.DEPLOYMENT_TOKEN }}
